name: RichNavigationIndexing
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  richnav:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
      node-version: '12.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - uses: microsoft/RichCodeNavIndexer@master
      with:
        languages: typescript
